Added buy hypha button and transaction
hypha-dao/dho-web-client pull request #712
Opened 2022-02-23 20:45 UTC by pugakn

* Neet to be tested in production as soon as deployed

2022-02-23 23:15 UTC, DaniPoot approved these changes

2022-02-23 23:16 UTC, DaniPoot requested changes
The merge is into Master?

2022-02-24 00:06 UTC, pugakn commented
> Is the merge into Master?

Yes, is for the old design on production

2022-02-24 00:09 UTC, DaniPoot approved these changes

2022-02-24 00:09 UTC, merged